version: 2.1
jobs:
  build:
    machine: true
    working_directory: /tmp/artifacts
    steps:
      - checkout
      - run: docker run -it -v $(pwd):/zap/ owasp/zap2docker-weekly zap.sh -cmd -quickurl https://example.com -quickout testreport.xml
      - store_artifacts:
         path: /tmp/artifacts
