version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mkdir artifacts
      - run: docker run -t owasp/zap2docker-stable zap-full-scan.py -t https://www.example.com
#       - run: docker run -t -v /tmp/artifacts:/zap/wrk/:rw owasp/zap2docker-weekly zap.sh -cmd -quickurl https://example.com -quickout "testreport.xml"
      - store_artifacts:
         path: /tmp/artifacts/
