version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker run -it owasp/zap2docker-weekly zap.sh -cmd -quickurl https://example.com -quickout testreport.xml
      - run: ls
      - store_artifacts:
         path: /zap/testreport.xml
