version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mkdir /tmp/artifacts
      #- run: docker run -t owasp/zap2docker-stable zap-full-scan.py -t https://www.example.com
      - run: if docker run -v /tmp/artifacts/:/zap/wrk/:rw -u root -t owasp/zap2docker-stable zap-baseline.py -t http://testphp.vulnweb.com/ -r testreport1.html; then exit 0; fi
      - store_artifacts:
         path: /tmp/artifacts
