version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mkdir /tmp/artifacts
      - run: docker run -t owasp/zap2docker-stable zap-full-scan.py -t https://www.example.com
      - run: docker run -v /tmp/artifacts/:/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://www.example.com  -r testreport.html
      - store_artifacts:
         path: /tmp/artifacts
