version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker run -it owasp/zap2docker-weekly zap.sh -cmd -quickurl https://staging.rently.com -quickout testreport.xml
      #- run: cat testreport.xml > 
      - store_artifacts:
         path: /zap/testreport.xml
