version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: mkdir ~/zap1
      - run: docker run -it owasp/zap2docker-weekly zap.sh -cmd -quickurl https://staging.rently.com -quickprogress > ~/zap1/report.xml 
      - store_artifacts:
         path: ~/zap1/testreport.html
